#!/usr/bin/env python3
"""Generate the standardized 10 mm open-cup mold STLs used by the fill plan."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "paper" / "molds"
MANIFEST = DEFAULT_OUT / "mold_manifest.md"

OUTER_MM = 14.0
CAVITY_MM = 10.0
HEIGHT_MM = 12.0
FLOOR_MM = 2.0


Point = tuple[float, float, float]
Triangle = tuple[Point, Point, Point]


def read_plan(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return [{k: (v or "").strip() for k, v in row.items()} for row in csv.DictReader(f)]


def rect_triangles(a: Point, b: Point, c: Point, d: Point) -> list[Triangle]:
    return [(a, b, c), (a, c, d)]


def open_cup_triangles() -> list[Triangle]:
    o = OUTER_MM / 2.0
    i = CAVITY_MM / 2.0
    z0 = 0.0
    zf = FLOOR_MM
    zh = HEIGHT_MM

    tris: list[Triangle] = []

    # Bottom.
    tris.extend(rect_triangles((-o, -o, z0), (o, -o, z0), (o, o, z0), (-o, o, z0)))

    # Outer walls.
    tris.extend(rect_triangles((-o, -o, z0), (-o, -o, zh), (o, -o, zh), (o, -o, z0)))
    tris.extend(rect_triangles((o, -o, z0), (o, -o, zh), (o, o, zh), (o, o, z0)))
    tris.extend(rect_triangles((o, o, z0), (o, o, zh), (-o, o, zh), (-o, o, z0)))
    tris.extend(rect_triangles((-o, o, z0), (-o, o, zh), (-o, -o, zh), (-o, -o, z0)))

    # Floor ring/top around the cavity bottom at z=FLOOR_MM.
    tris.extend(rect_triangles((-o, -o, zf), (o, -o, zf), (i, -i, zf), (-i, -i, zf)))
    tris.extend(rect_triangles((o, -o, zf), (o, o, zf), (i, i, zf), (i, -i, zf)))
    tris.extend(rect_triangles((o, o, zf), (-o, o, zf), (-i, i, zf), (i, i, zf)))
    tris.extend(rect_triangles((-o, o, zf), (-o, -o, zf), (-i, -i, zf), (-i, i, zf)))

    # Inner cavity walls.
    tris.extend(rect_triangles((-i, -i, zf), (i, -i, zf), (i, -i, zh), (-i, -i, zh)))
    tris.extend(rect_triangles((i, -i, zf), (i, i, zf), (i, i, zh), (i, -i, zh)))
    tris.extend(rect_triangles((i, i, zf), (-i, i, zf), (-i, i, zh), (i, i, zh)))
    tris.extend(rect_triangles((-i, i, zf), (-i, -i, zf), (-i, -i, zh), (-i, i, zh)))

    # Top rim.
    tris.extend(rect_triangles((-o, -o, zh), (-i, -i, zh), (i, -i, zh), (o, -o, zh)))
    tris.extend(rect_triangles((o, -o, zh), (i, -i, zh), (i, i, zh), (o, o, zh)))
    tris.extend(rect_triangles((o, o, zh), (i, i, zh), (-i, i, zh), (-o, o, zh)))
    tris.extend(rect_triangles((-o, o, zh), (-i, i, zh), (-i, -i, zh), (-o, -o, zh)))

    return tris


def normal(tri: Triangle) -> Point:
    (ax, ay, az), (bx, by, bz), (cx, cy, cz) = tri
    ux, uy, uz = bx - ax, by - ay, bz - az
    vx, vy, vz = cx - ax, cy - ay, cz - az
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    length = (nx * nx + ny * ny + nz * nz) ** 0.5
    if length == 0:
        return (0.0, 0.0, 0.0)
    return (nx / length, ny / length, nz / length)


def write_ascii_stl(path: Path, solid_name: str, triangles: list[Triangle]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as f:
        f.write(f"solid {solid_name}\n")
        for tri in triangles:
            nx, ny, nz = normal(tri)
            f.write(f"  facet normal {nx:.6g} {ny:.6g} {nz:.6g}\n")
            f.write("    outer loop\n")
            for x, y, z in tri:
                f.write(f"      vertex {x:.6g} {y:.6g} {z:.6g}\n")
            f.write("    endloop\n")
            f.write("  endfacet\n")
        f.write(f"endsolid {solid_name}\n")


def write_manifest(plan_rows: list[dict[str, str]], generated: list[Path]) -> None:
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    with MANIFEST.open("w") as f:
        f.write("# Standard Mold Manifest\n\n")
        f.write("Generated by `tools/generate_standard_molds.py` from `paper/fill_trial_plan.csv`.\n\n")
        f.write("## Geometry\n\n")
        f.write(f"- Outer size: {OUTER_MM:g} mm x {OUTER_MM:g} mm\n")
        f.write(f"- Cavity: {CAVITY_MM:g} mm x {CAVITY_MM:g} mm open cup\n")
        f.write(f"- Height: {HEIGHT_MM:g} mm\n")
        f.write(f"- Floor thickness: {FLOOR_MM:g} mm\n")
        f.write("- Intended mold material/tool: PETG on T0 with 0.4 mm nozzle\n\n")
        f.write("## Files\n\n")
        f.write("| plan_id | file | schedule | temp C | flow mm3/s |\n")
        f.write("| --- | --- | --- | --- | --- |\n")
        for row, path in zip(plan_rows, generated):
            f.write(
                "| "
                + " | ".join([
                    row.get("plan_id", ""),
                    f"`{path.relative_to(ROOT)}`",
                    row.get("schedule", ""),
                    row.get("injection_temp_c", ""),
                    row.get("flow_mm3_s", ""),
                ])
                + " |\n"
            )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--plan", type=Path, default=Path("paper/fill_trial_plan.csv"))
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()

    plan_rows = sorted(read_plan(args.plan.resolve()), key=lambda row: int(row.get("run_order", "0") or 0))
    triangles = open_cup_triangles()
    generated: list[Path] = []
    out_dir = args.out_dir.resolve()
    for row in plan_rows:
        plan_id = row.get("plan_id", "")
        if not plan_id:
            continue
        path = out_dir / f"{plan_id}_mold.stl"
        write_ascii_stl(path, f"{plan_id}_standard_open_cup_mold", triangles)
        generated.append(path)

    write_manifest(plan_rows, generated)
    print(MANIFEST)
    print(f"molds={len(generated)}")
    print(f"triangles_per_mold={len(triangles)}")
    return 0 if len(generated) == len(plan_rows) and len(generated) >= 10 else 1


if __name__ == "__main__":
    raise SystemExit(main())
